tasks:
  - label: RdfConnectionExplainStatic-turtle
    class: RdfConnectionExplainStatic
    params:
      - graphFormat: 'turtle'
  - label: RdfConnectionExplainStatic-jsonld
    class: RdfConnectionExplainStatic
    params:
      - graphFormat: 'json-ld'
  - label: RdfConnectionExplainStatic-xml
    class: RdfConnectionExplainStatic
    params:
      - graphFormat: 'xml'
  - label: RdfConnectionExplainStatic-nt
    class: RdfConnectionExplainStatic
    params:
      - graphFormat: 'ntriples'
  - label: "Text2SparqlExecEvalListBeastiary-turtle-subgraph"
    class: "Text2SparqlExecEvalListBeastiary"
    params:
      - kgInfoType: "subgraph"
        kgInfoFormat: "turtle"
  - label: "Text2SparqlExecEvalListBeastiary-turtle-schema"
    class: "Text2SparqlExecEvalListBeastiary"
    params:
      - kgInfoType: "schema"
        kgInfoFormat: "turtle"
  - label: "Text2SparqlExecEvalListBeastiary-turtle-subschema"
    class: "Text2SparqlExecEvalListBeastiary"
    params:
      - kgInfoType: "subschema"
        kgInfoFormat: "turtle"
  - Text2SparqlExecEvalListOrganizational
  - Text2SparqlExecEvalListOrgaNumerical
  - Text2SparqlExecEvalListCoypuMini
  - SparqlSyntaxFixingListLcQuad
  - label: "Text2AnswerListOrga-turtle"
    class: "Text2AnswerListOrganizational"
    params:
      - graphFormat: "turtle"
  - label: "Text2AnswerListOrga-jsonld"
    class: "Text2AnswerListOrganizational"
    params:
      - graphFormat: "json-ld"
  - label: "Sparql2AnswerListOrga-turtle"
    class: "Sparql2AnswerListOrganizational"
    params:
      - graphFormat: "turtle"
  - label: "Sparql2AnswerListOrga-jsonld"
    class: "Sparql2AnswerListOrganizational"
    params:
      - graphFormat: "json-ld"
  - label: "RdfFriendCount-turtle-1"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "1"
        graphFormat: "turtle"
  - label: "RdfFriendCount-turtle-2"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "2"
        graphFormat: "turtle"
  - label: "RdfFriendCount-jsonld-1"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "1"
        graphFormat: "json-ld"
  - label: "RdfFriendCount-jsonld-2"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "2"
        graphFormat: "json-ld"
  - label: "RdfFriendCount-xml-1"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "1"
        graphFormat: "xml"
  - label: "RdfFriendCount-xml-2"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "2"
        graphFormat: "xml"
  - label: "RdfFriendCount-nt-1"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "1"
        graphFormat: "ntriples"
  - label: "RdfFriendCount-nt-2"
    class: RdfFriendCount
    params:
      - specialAddKnowsCount: "2"
        graphFormat: "ntriples"
  - label: "RdfSyntaxFixList-turtle"
    class: RdfSyntaxFixList
    params:
      - graphFormat: "turtle"
  - label: "RdfSyntaxFixList-jsonld"
    class: RdfSyntaxFixList
    params:
      - graphFormat: "json-ld"
  - label: "RdfSyntaxFixList-nt"
    class: RdfSyntaxFixList
    params:
      - graphFormat: "nt"
####
# Model definitions
####
models:
  ### Google-Models
  - label: Gemini-1.0-Pro
    class: ModelGoogle
    params:
      - model: 'gemini-1.0-pro'
  - label: Gemini-1.5-Pro-001
    class: ModelGoogle
    params:
      - model: 'models/gemini-1.5-pro-001'
  - label: Gemini-1.5-Pro-002
    class: ModelGoogle
    params:
      - model: 'models/gemini-1.5-pro-002'
  - label: Gemini-1.5-Flash-001
    class: ModelGoogle
    params:
      - model: 'models/gemini-1.5-flash-001'
  - label: Gemini-1.5-Flash-002
    class: ModelGoogle
    params:
      - model: 'models/gemini-1.5-flash-002'
  - label: Gemini-1.5-Pro-Exp-2024-08
    class: ModelGoogle
    params:
      - model: 'gemini-1.5-pro-exp-0827'
  - label: "Gemini-2.0-Flash-exp"
    class: "ModelGoogle"
    params:
      - model: 'gemini-2.0-flash-exp'
  ### OpenAI-Models
  - label: "GPT-3.5t 2024-01"
    class: ModelGpt
    params:
      - model: "gpt-3.5-turbo-0125"
  - label: GPT-3.5t 3.23
    class: ModelGpt
    params:
      - model: "gpt-3.5-turbo-0301"
  # - label: GPT-3.5t 6.23
  #   class: ModelGpt
  #   params:
  #     - model: "gpt-3.5-turbo-0613"
  - label: GPT-3.5t16k 6.23
    class: ModelGpt
    params:
      - model: "gpt-3.5-turbo-16k-0613" 
  - label: GPT-3.5t16k 11.23
    class: ModelGpt
    params:
      - model: "gpt-3.5-turbo-1106" #has 16k
  - label: GPT-4 3.23
    class: ModelGpt 
    params:
      - model: "gpt-4-0314"
  # - label: GPT-4 6.23
  #   class: ModelGpt 
  #   params:
  #     - model: "gpt-4-0613"
  - label: GPT-4t 11.23
    class: ModelGpt
    params:
      - model: "gpt-4-1106-preview" # has 128k
  - label: "GPT-4t 2024-04"
    class: ModelGpt
    params:
      - model: "gpt-4-turbo-2024-04-09"
  - label: "GPT-4o 2024-05"
    class: ModelGpt
    params:
      - model: "gpt-4o-2024-05-13"
  - label: "GPT-4o 2024-08"
    class: ModelGpt
    params:
      - model: "gpt-4o-2024-08-06"
  - label: "GPT-4o-2024-11"
    class: ModelGpt
    params:
      - model: "gpt-4o-2024-11-20"
  - label: "GPT-4o-mini 2024-07"
    class: ModelGpt
    params:
      - model: "gpt-4o-mini-2024-07-18"
  - label: "GPT-o1-mini-2024-09"
    class: ModelGpt
    params:
      - model: "o1-mini-2024-09-12"
  - label: "GPT-o1-2024-09p"
    class: ModelGpt
    params:
      - model: "o1-preview-2024-09-12"
  - label: "GPT-o1-2024-12"
    class: ModelGpt
    params:
      - model: "o1"
  ### Claude-Models
  - label: Claude-inst-1.0
    class: ModelClaude
    params:
      - model: "claude-instant-1.0"
  - label: Claude-inst-1.1
    class: ModelClaude
    params:
      - model: "claude-instant-1.1"
  - label: Claude-inst-1.2
    class: ModelClaude
    params:
      - model: "claude-instant-1.2"
  - label: Claude-1.2
    class: ModelClaude
    params:
      - model: "claude-1.2"
  - label: Claude-1.3
    class: ModelClaude
    params:
      - model: "claude-1.3"
  - label: Claude-1.3-100k
    class: ModelClaude
    params:
      - model: "claude-1.3-100k"
  - label: Claude-2.0
    class: ModelClaude
    params:
      - model: "claude-2.0" #has 100k
  - label: Claude-2.1
    class: ModelClaude
    params:
      - model: "claude-2.1" #has 200k
  - label: Claude-3-haiku
    class: ModelClaude
    params:
      - model: "claude-3-haiku-20240307" #has 200k input, 4k output limit
  - label: Claude-3-sonnet
    class: ModelClaude
    params:
      - model: "claude-3-sonnet-20240229" #has 200k input, 4k output limit
  - label: Claude-3-opus
    class: ModelClaude
    params:
      - model: "claude-3-opus-20240229" #has 200k input, 4k output limit
  - label: "Claude-3.5-sonnet 2024-06"
    class: ModelClaude
    params:
      - model: "claude-3-5-sonnet-20240620" #has 200k input, 8k output limit
  - label: "Claude-3.5-sonnet 2024-10"
    class: ModelClaude
    params:
      - model: "claude-3-5-sonnet-20241022" #has 200k input, 8k output limit
  - label: Claude-3.5-haiku
    class: ModelClaude
    params:
      - model: "claude-3-5-haiku-20241022" #has 200k input, 8k output limit
sizes:
  - 1000
iterations: 20
